name: Build
on:
  push:
    branches: ["[0-9]+.[0-9]+.x"]
  pull_request:
    types: [opened, synchronize]

jobs:
     build:
       runs-on: ubuntu-latest
       timeout-minutes: 10
       permissions:
         contents: read
       steps:
         - uses: actions/checkout@v3

  @@ -17,7 +22,9 @@ jobs:
       - name: Validate Gradle wrapper
         uses: gradle/wrapper-validation-action@v1

       - name: Build
         uses: gradle/gradle-build-action@v2
         with:
           arguments: build
         env:
           CI: true